version: "3.8"
services:
  eleonore-service:
    container_name: eleonore-service
    build: .
    ports:
      - "8181:8181"
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - eleonore-database
      - eleonore-redis
    networks:
      - eleonore-network
  eleonore-database:
    container_name: eleonore-database
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=eleonore
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - eleonore-network
  eleonore-redis:
    container_name: eleonore-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - eleonore-network
networks:
  eleonore-network:
    driver: bridge
